attention: false
batch: 1
commit: c13b11caadb9124b236bab2fc38f5f3ce9810161
constant_dur: 100000.0
cuda_diffuse: false
data_skip: true
decay_dur: 500000.0
dry_run: false
embeddings_dir: ./data/embeddings
embeddings_key: reference
epochs: 100
inf_freq: 1
inf_mols: 100
inf_step: 0.5
inf_type: rate
inference_mode: false
limit_mols: null
lin_nf: 1
lin_self: false
lm_edge_dim: 128
lm_node_dim: 256
lr: 0.0003
lr_end: 1
lr_start: 1
max_len: 1500
no_edge_embs: false
no_radius_sqrt: false
num_workers: 4
omegafold_num_recycling: 4
order: 1
parity: true
pdb_dir: ./data/pdb_chains
print_freq: 100
radius_emb_dim: 50
radius_emb_max: 50
radius_emb_type: gaussian
resi_conv_layers: 6
resi_fc_dim: 128
resi_ns: 32
resi_ntps: 16
resi_ntpv: 4
resi_nv: 4
resi_pos_emb_dim: 16
resume: null
save_freq: 1
sde_a: 0.20775623268698062
sde_b: 0
sde_weight: 1
sh_lmax: 2
splits: splits/limit256.csv
t_emb_dim: 32
t_emb_type: sinusoidal
time: 1679575156475
tmax: 1000000.0
tmin: 0.001
train_Hf: 2
train_cutoff: 5
train_kmin: 5
train_rmsd_max: 0.0
train_skew: 0
train_tmin: 0.01
wandb: harmonic-resi
warmup_dur: 10000.0
workdir: ./workdir
